### ISSUE TITLE
Read sdks from .sdkmanrc

### ISSUE THREAD

**Issue by breucode** [eddumelendez/sdkman-action#13]
Instead of specifying the sdks in the workflow itself it would be nice to read the sdks from the .sdkmanrc file

**Comment by eddumelendez** [comment]
See https://github.com/sdkman/sdkman-action/pull/11

**Comment by fnobilia** [comment]
I've tried out #11, but I get this error

```
Run sdkman/sdkman-action@master
Run candidate=
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1149  100  1149    0     0   [48](https://github.com/fnobilia/serverless-slack-bot/actions/runs/4702791134/jobs/8340481096#step:3:50)66      0 --:--:-- --:--:-- --:--:--  4868
hook_post__.sh: line 1: syntax error near unexpected token `newline'
Error: Process completed with exit code 2.
```

my `.sdkmanrc` is
```
java=22.1.0.r17-grl
gradle=7.5
```

and my github workflow is
```
name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up SDK
        uses: sdkman/sdkman-action@master
        id: sdkman
      - name: Show Java version
        run: java -version
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
```

Any suggestion?
