### ISSUE TITLE
Full install of candidates and switching between them

### ISSUE THREAD

**Issue by msgilligan** [eddumelendez/sdkman-action#5]
It would be nice to be able to use this action to install multiple candidates, including multiple versions of the JDK and be able to do things like (for example) run Gradle (6.7 or later) with one jDK and use another JDK for compiling with the Gradle toolchains feature.

**Comment by eddumelendez** [comment]
You can use matrix to install different jdks. Look at the workflow we have https://github.com/sdkman/sdkman-action/blob/master/.github/workflows/workflow.yml

**Comment by msgilligan** [comment]
I want to install **multiple** jdks in a single build, so matrix won't work.

In fact, i'd like a matrix that changes two variables `${{ matrix.gradleJDK }}` and `${{ matrix.javaToolchainJDK }}` so I can run Gradle with a different JDK than I use to run `javac`, `jlink`, etc.

**Comment by eddumelendez** [comment]
I think the following step can be used multiple times because the only thing it does is to download an specific version but `setup-java` action needs to setup the JAVA_HOME environment.

```
- name: Setup Java ${{ matrix.version }}
      id: sdkman
      uses: ./
      with:
        candidate: java
        version: ${{ matrix.version }}
```

So, this is out of scope.
