### ISSUE TITLE
Unable to use the action

### ISSUE THREAD

**Issue by igorwojda** [eddumelendez/sdkman-action#6]
workflow.yml
```
- uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 15.0.0

- name: Set up JDK
  uses: actions/setup-java@v1
  with:
    java-version: 15.0.0
```

Error
```
Run sdkman/sdkman-action@master
  with:
    candidate: java
    version: 15.0.0
  env:
    JAVA_HOME_15.0.0_x64: /opt/hostedtoolcache/jdk/15.0.0/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/15.0.0/x64
    JAVA_HOME_15_0_0_X64: /opt/hostedtoolcache/jdk/15.0.0/x64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1068  100  1068    0     0  20538      0 --:--:-- --:--:-- --:--:-- 20538
Download has failed, aborting!

Can not install java 15.0.0 at this time...
Error: Process completed with exit code 1.
```

**Comment by eddumelendez** [comment]
if you have sdkman installed locally. You can run `sdk list java` and use the identifier in the version field. So, for example it will looks like this

```
- uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 15.0.2.7.1-amzn
```

![Screen Shot 2021-02-04 at 19 14 58](https://user-images.githubusercontent.com/1810547/106976036-4ab4af80-671d-11eb-9ee3-8a14a69ad3e5.png)
